### PR TITLE
Add dns fetch functionality

### PR DESCRIPTION
**Pull request by Maunty**
Table resources were generated according to already impemented machinery.

Iteration via dns zones for records fetch are implemented as embeded table via <Relations> machinary.

Primary key for records table was formed over zone_id+name+type colums. In order to implement this i was forced to skip fields `name` and `type` and define required colums as extraColums. Dont sure if this is optimal way of implementation provided by CQ.

### CODE REVIEW

**Review by kabachook — APPROVED** [review]

**Comment by Maunty** [comment]
@kabachook CI is awaiting some approve actions. I am not familiar with GH Actions, my PR doesn't contain changes of any CI related configurations, so this is not related to its content. Hope you can find some time to solve this issue.

I would be happy to have this functionality in upstream.

**Comment by kabachook** [comment]
Hi, @Maunty! Since i'am not a maintainer my approve doesn't trigger CI checks or allow to merge. @GennadySpb @valyankilyan please review

**Review by valyankilyan — APPROVED** [review]
LGTM

**Comment by kabachook** [comment]
Hi, @Maunty. Due to internal refactor this has been implemented in https://github.com/yandex-cloud/cq-source-yc/commit/ac5dfca499820b151fc5de961edd211e35897687. It will be published in v1 release soon.

**Comment by kabachook** [comment]
@Maunty Released https://github.com/yandex-cloud/cq-source-yc/releases/tag/v1.0.0

**Pull request closed without merging**
